main
string main.HOOK_FILENAME
string main.HOOK_TEMPLATE
string main.api_url
string main.dashboard_url
def main.install_git_hook(location, token)
Install a post-commit hook in the specified location. Args: location (str): The path to the Git repository. token (str): The token to be used in the hook. Raises: SystemExit: If the hooks directory does not exist. Returns: None
Referenced by main.
def main.uninstall_git_hook(location)
Uninstalls the post-commit hook from the specified location. Parameters: - location (str): The path to the directory containing the Git repository. Returns: None
Referenced by main.
def main.generate_doc(token, file_path=None, complete_folder_path=None, git_folder_path=None)
Generates documentation based on the given parameters. Parameters: - token (str): The API token for authentication. - file_path (str, optional): The path to a specific file to generate documentation for. - complete_folder_path (str, optional): The path to a complete folder to generate documentation for. - git_folder_path (str, optional): The path to a Git repository folder to generate documentation for.
Referenced by main.
def main.commit_code(str gf_path, str token, str message, bool open_terminal)
Referenced by main.
def main.save_credentials(api_key)
Save the token and API keys in the .penify file in the user's home directory.
Referenced by login.
def main.login()
Open the login page in a web browser and listen for the redirect URL to capture the token.
References save_credentials.
Referenced by main.
def main.get_token(passed_token)
Get the token based on priority: 1. Passed parameter 2. Environment variable 3. Config file
Referenced by main.
def main.main()
Main entry point for the Penify CLI tool. This function sets up the command-line interface (CLI) for managing Git hooks and generating documentation. It utilizes the argparse library to define various subcommands, including installing and uninstalling Git hooks, generating documentation, committing changes, and logging in to obtain an API token. The function also handles the retrieval of the API token based on user input or environment variables and executes the appropriate subcommand based on user selection.
References commit_code, utils.find_git_parent, generate_doc, get_token, install_git_hook, login, uninstall_git_hook.