import sys
from pathlib import Path

HOOK_FILENAME = "post-commit"
HOOK_TEMPLATE = """#!/bin/sh
# This is a post-commit hook generated by penifycli.

penifycli -t {token} -gf {git_folder_path}
"""

def install_git_hook(location, token):
    """Install a post-commit hook in the specified location.

    This function sets up a post-commit hook script in the Git hooks
    directory of the specified repository location. It checks if the hooks
    directory exists, and if it does, it creates a hook script with the
    provided token and makes it executable. The hook script is used to
    automate tasks after a commit is made.

    Args:
        location (str): The path to the Git repository where the hook should be installed.
        token (str): A token that will be included in the hook script for authentication or
            other purposes.
    """
    hooks_dir = Path(location) / ".git/hooks"
    hook_path = hooks_dir / HOOK_FILENAME
    
    if not hooks_dir.exists():
        print(f"Error: The hooks directory {hooks_dir} does not exist.")
        sys.exit(1)
    
    hook_content = HOOK_TEMPLATE.format(token=token, git_folder_path=location)
    hook_path.write_text(hook_content)
    hook_path.chmod(0o755)  # Make the hook script executable

    print(f"Post-commit hook installed in {hook_path}")

def uninstall_git_hook(location):
    """Uninstalls the post-commit hook from the specified location.

    This function removes the post-commit hook file from the .git/hooks
    directory at the given location. If the hook file exists, it will be
    deleted, and a confirmation message will be printed. If the hook file
    does not exist, a message indicating that no hook was found will be
    printed.

    Args:
        location (str): The directory path where the .git/hooks directory
            is located.
    """
    hook_path = Path(location) / ".git/hooks" / HOOK_FILENAME
    
    if hook_path.exists():
        hook_path.unlink()
        print(f"Post-commit hook uninstalled from {hook_path}")
    else:
        print(f"No post-commit hook found in {hook_path}")
